### PR TITLE
Creating a css project 

### PR DESCRIPTION
**Pull request by Spyder15**
detect key pressed with index,style, and also readme file created

### CODE REVIEW

**Comment by lovishprabhakar** [comment]
Nice work @Spyder15 but here are a few things you need to do:
1. You should create an issue before creating a pull request in any repository. Keep this in mind for future contributions also.
2. You have placed your project in the "MLSA Event-101" folder whereas it should be in the "Know Your Code Folder".
3. In your "readme.md" file, try to add some screenshots of the interface that you have talked about. This will make your project clearer to the viewers.

**Comment by lovishprabhakar** [comment]
@Spyder15 I see that you haven't made any changes since my last comment. I would like to remind you that you have 2 days to complete your contribution or this Pull Request will be closed.
If you are stuck somewhere or have any doubts, feel free to ask them here.

**Comment by cyberbuddy-manas** [comment]
@lovishprabhakar  Kindly make the corrections and merge this request

**Comment by Spyder15** [comment]
i have done

**Pull request merged**
