### PR TITLE
Adding new C++ files 

### PR DESCRIPTION
**Pull request by shubhamk90**
Added two new c++ files
(1) Exception handling in C++
(2) Templates in C++

### CODE REVIEW

**Comment by cyberbuddy-manas** [comment]
@shubhamk90 It's a great contribution!! Could you please share the program you're enrolled in from where you got to know about this repository.

**Comment by shubhamk90** [comment]
@cyberbuddy-manas I'm a beginner and  just Exploring Github and found this repository to contribute

**Comment by cyberbuddy-manas** [comment]
You're going great, I'll merge the pull request. Also kindly share your
email address in comments. Also join our group where we share stuff related
to technology and other opportunities

https://chat.whatsapp.com/G1aTUUifXJZ3jJw1RFHlEg

**Comment by shubhamk90** [comment]
E-mail:-  sharmashubham52y@gmail.com

**Pull request merged**
