### PR TITLE
Added HTML,CSS project as mentioned in the issue #233

### PR DESCRIPTION
**Pull request by kartikthakur7107**
Added a simple HTML,CSS project. Linktree clone

### CODE REVIEW

**Comment by lovishprabhakar** [comment]
Great work @kartikthakur7107! Just make the changes I reviewed and your contribution is good to go.

**Comment by kartikthakur7107** [comment]
@lovishprabhakar what changes do I need to make? BWT you haven't mentioned any

**Comment by lovishprabhakar** [comment]
image
Just move this image URL two lines below. It will make the readme file look better

**Comment by kartikthakur7107** [comment]
@lovishprabhakar Done, Updated readme. Ty for letting me know about the error.

**Comment by lovishprabhakar** [comment]
Also, @kartikthakur7107, your readme file should have another step describing that whoever uses this clone needs to replace your profile links with their own in the HTML file. You can also attach a picture of the links in the HTML file. Make it the 4th step in your readme and then your PR is good to go.

**Comment by kartikthakur7107** [comment]
@lovishprabhakar Done, Added the 4th step to change links in the HTML file.

**Comment by lovishprabhakar** [comment]
Good work @kartikthakur7107. Keep it up and do help the others contribute!

**Comment by kartikthakur7107** [comment]
> Good work @kartikthakur7107. Keep it up and do help the others contribute!

Yah sure, Helping them with creating Issue and PR's and offcourse clearing some git commands.

**Pull request merged**
