### PR TITLE
Adding python files #35

### PR DESCRIPTION
**Pull request by Kritikmahajan**
I will be adding dictionary  methods. please assign this issue to me @lovishprabhakar02

### CODE REVIEW

**Comment by Kritikmahajan** [comment]
Good experience

**Comment by Kritikmahajan** [comment]
I  am not showing as the assignees of the python files. have i done  it right ?

**Comment by lovishprabhakar02** [comment]
Yes @Kritikmahajan you have done everything right, well done! There seems to be some issue as your name is not visible in the assignees list. I will look into it. Just one thing, before making a PR, you need to comment on the issue about what you are going to do

**Comment by Kritikmahajan** [comment]
Now I am included in the contributors but not as an assignees

**Comment by lovishprabhakar02** [comment]
Your name is now visible in the assignees @Kritikmahajan .

**Pull request merged**
