### PR TITLE
#234

### PR DESCRIPTION
**Pull request by vishal-cse02**

### CODE REVIEW

**Comment by lovishprabhakar** [comment]
Good going @vishal-cse02! Just update your readme file and add some more details about the webpage to it, maybe a screenshot too and your contribution would be good to go!

**Comment by lovishprabhakar** [comment]
Well done @vishal-cse02! One last thing to do is fetch the upstream so that your fork does not lie behind the master repository. Then your PR will be good to merge.

How to fetch upstream, open your fork of the repository and follow this:

image

And always remember to fetch upstream before contributing to any repository.

**Comment by vishal-cse02** [comment]
Thank you so much sir for your guidance. Really appreciate it!!

**Comment by lovishprabhakar** [comment]
> Thank you so much sir for your guidance. Really appreciate it!!

No worries Vishal, all that's left is to rename **"readme.md.txt"** to **"readme.md"**.

**Comment by vishal-cse02** [comment]
Please check now is it done

**Comment by lovishprabhakar** [comment]
Congratulations on your first open-source contribution! @vishal-cse02

**Comment by vishal-cse02** [comment]
Thanks !!

**Pull request merged**
